version: '3'

services:
  consul:
      image: consul:1.11.11
      ports:
        - "8300:8300"
        - "8301:8301"
        - "8302:8302"
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"
  redis:
      image: redis:7.0.5
      ports:
        - "6379:6379"
  mysql:
      image: mysql:5.7.40
      ports:
        - "3306:3306"
      environment:
         MYSQL_ROOT_PASSWORD: 123456
         MYSQL_DATABASE: spring_cloud